### ISSUE TITLE
Error at the first step of search in the connector

### ISSUE THREAD

**Issue by nikolaeva31** [happy-travel/juniper-connector#146]
1. Request:
```
{
	 "accommodationIds": ["JP02647T"],
    "checkInDate": "2022-09-22T01:00:00.000Z",
    "checkOutDate": "2022-09-26T01:00:00.000Z",
  	"filters": "AvailableOnly",  
    "nationality": "RU",
    "residency": "RU",
    "rooms": [
				{
		"adultsNumber": 2,
		"childrenNumber": 0,
		"childrenAges": []
	}
		]
}
```

**AR**: Response:
```
{
    "status": 400,
    "detail": "Code: `JP_SEARCH_BOOKDATE`, Text: ` XML seems to be incomplete or wrong. Reservation out of date`, Type: ``"
}
```

Response from supplier: 
`<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><HotelAvailResponse xmlns="http://www.juniper.es/webservice/2007/"><AvailabilityRS Url="http://xml-uat.bookingengine.es" TimeStamp="2022-09-19T10:07:08.2811476+02:00" IntCode="="><Errors><Error Text=" XML seems to be incomplete or wrong. Reservation out of date" Code="JP_SEARCH_BOOKDATE" /></Errors></AvailabilityRS></HotelAvailResponse></soap:Body></soap:Envelope>`

**Comment by PKorovinPromo-Z** [comment]
Supplier response: Please try to validate with a date that is not so close. The product in test is somewhat limited, please try to send the request with a date that is not so close.
